export const types = [
  "Normal",
  "Fire",
  "Water",
  "Electric",
  "Grass",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
];

export const typeChart: Record<string, Record<string, number>> = {
  Normal: { Rock: 0.5, Ghost: 0, Steel: 0.5 },
  Fire: {
    Fire: 0.5,
    Water: 0.5,
    Grass: 2,
    Ice: 2,
    Bug: 2,
    Rock: 0.5,
    Dragon: 0.5,
    Steel: 2,
  },
  Water: { Fire: 2, Water: 0.5, Grass: 0.5, Ground: 2, Rock: 2, Dragon: 0.5 },
  Electric: {
    Water: 2,
    Electric: 0.5,
    Grass: 0.5,
    Ground: 0,
    Flying: 2,
    Dragon: 0.5,
  },
  Grass: {
    Fire: 0.5,
    Water: 2,
    Grass: 0.5,
    Poison: 0.5,
    Ground: 2,
    Flying: 0.5,
    Bug: 0.5,
    Rock: 2,
    Dragon: 0.5,
    Steel: 0.5,
  },
  Ice: {
    Fire: 0.5,
    Water: 0.5,
    Grass: 2,
    Ice: 0.5,
    Ground: 2,
    Flying: 2,
    Dragon: 2,
    Steel: 0.5,
  },
  Fighting: {
    Normal: 2,
    Ice: 2,
    Poison: 0.5,
    Flying: 0.5,
    Psychic: 0.5,
    Bug: 0.5,
    Rock: 2,
    Ghost: 0,
    Dark: 2,
    Steel: 2,
    Fairy: 0.5,
  },
  Poison: {
    Grass: 2,
    Poison: 0.5,
    Ground: 0.5,
    Rock: 0.5,
    Ghost: 0.5,
    Steel: 0,
    Fairy: 2,
  },
  Ground: {
    Fire: 2,
    Electric: 2,
    Grass: 0.5,
    Poison: 2,
    Flying: 0,
    Bug: 0.5,
    Rock: 2,
    Steel: 2,
  },
  Flying: {
    Electric: 0.5,
    Grass: 2,
    Fighting: 2,
    Bug: 2,
    Rock: 0.5,
    Steel: 0.5,
  },
  Psychic: { Fighting: 2, Poison: 2, Psychic: 0.5, Dark: 0, Steel: 0.5 },
  Bug: {
    Fire: 0.5,
    Grass: 2,
    Fighting: 0.5,
    Poison: 0.5,
    Flying: 0.5,
    Psychic: 2,
    Ghost: 0.5,
    Dark: 2,
    Steel: 0.5,
    Fairy: 0.5,
  },
  Rock: {
    Fire: 2,
    Ice: 2,
    Fighting: 0.5,
    Ground: 0.5,
    Flying: 2,
    Bug: 2,
    Steel: 0.5,
  },
  Ghost: { Normal: 0, Psychic: 2, Ghost: 2, Dark: 0.5 },
  Dragon: { Dragon: 2, Steel: 0.5, Fairy: 0 },
  Dark: { Fighting: 0.5, Psychic: 2, Ghost: 2, Dark: 0.5, Fairy: 0.5 },
  Steel: {
    Fire: 0.5,
    Water: 0.5,
    Electric: 0.5,
    Ice: 2,
    Rock: 2,
    Fairy: 2,
    Steel: 0.5,
  },
  Fairy: {
    Fire: 0.5,
    Fighting: 2,
    Poison: 0.5,
    Dragon: 2,
    Dark: 2,
    Steel: 0.5,
  },
};

// add from shaoke
const spriteNameMap: Record<string, string> = {
  // From original spriteNameMap
  "mewtwo-mega-x": "mewtwo-megax",
  "mewtwo-mega-y": "mewtwo-megay",
  "charizard-mega-x": "charizard-megax",
  "charizard-mega-y": "charizard-megay",
  "necrozma-dawn-wings": "necrozma-dawnwings",
  "necrozma-dusk-mane": "necrozma-duskmane",
  "keldeo-ordinary": "keldeo",
  "wormadam-plant": "wormadam",
  "wormadam-sandy": "wormadam-sandy",
  "wormadam-trash": "wormadam-trash",

  // From showdownNameMap
  "calyrex-shadow-rider": "calyrex-shadow",
  "calyrex-ice-rider": "calyrex-ice",
  "zacian-crowned": "zacian-crowned",
  "zamazenta-crowned": "zamazenta-crowned",
  "urshifu-rapid-strike": "urshifu-rapid-strike",
  "flutter mane": "fluttermane",
  "chien-pao": "chienpao",
  "samurott-hisui": "samurott-hisui",
  "landorus-therian": "landorus-therian",
  "landorus-incarnate": "landorus",
  "flutter-mane": "fluttermane",
  "tornadus-incarnate": "tornadus",
  "thundurus-incarnate": "thundurus",
  "raging-bolt": "ragingbolt",
  "urshifu-rapid": "urshifu-rapidstrike",
  "urshifu-single": "urshifu",
  "indeedee-female": "indeedee-f",
  "chi-yu": "chiyu",
  "iron-hands": "ironhands",
  "roaring-moon": "roaringmoon",
  "iron-bundle": "ironbundle",
  "ting-lu": "https://play.pokemonshowdown.com/sprites/gen5/tinglu.png",
  "tatsugiri-curly": "tatsugiri",

  // more edits to pngs
  "squawkabilly-yellow-plumage": "squawkabilly-yellow",
  "squawkabilly-blue-plumage": "squawkabilly-blue",
  "squawkabilly-green-plumage": "squawkabilly",
  squawkabilly: "squawkabilly-white",
  "maushold-three": "maushold",
  "dudunsparce-two-segment": "dudunsparce",
  "gumshoos-totem": "gumshoos",
  "meloetta-aria": "meloetta",
  "porygon-z": "porygonz",
  "marowak-totem": "marowak",
  "iron-moth": "ironmoth",
  "gouging-fire": "gougingfire",
  "basculin-blue-striped": "basculin-bluestriped",
  "basculin-white-striped": "basculin-whitestriped",
  "greninja-battle-bond": "greninja",
  "araquanid-totem": "araquanid",
  "tapu-fini": "tapufini",
  "basculegion-male": "basculegion",
  "basculegion-female": "basculegion-f",
  "palafin-zero": "palafin-hero",
  "walking-wake": "walkingwake",
  "ho-oh": "hooh",
  "pikachu-rock-star": "pikachu-rockstar",
  "pikachu-pop-star": "pikachu-popstar",
  "pikachu-original-cap": "pikachu-original",
  "pikachu-hoenn-cap": "pikachu-hoenn",
  "pikachu-sinnoh-cap": "pikachu-sinnoh",
  "pikachu-unova-cap": "pikachu-unova",
  "pikachu-kalos-cap": "pikachu-kalos",
  "pikachu-alola-cap": "pikachu-alola",
  "pikachu-partner-cap": "pikachu-partner",
  "pikachu-world-cap": "pikachu-world",
  "oricorio-pom-pom": "oricorio",
  "togedemaru-totem": "togedemaru",
  "tapu-koko": "tapukoko",
  "tapu-bulu": "tapubulu",
  "tapu-lele": "tapulele",
  "toxtricity-amped": "toxtricity",
  "toxtricity-low-key": "toxtricity-lowkey",
  "toxtricity-amped-gmax": "toxtricity-gmax",
  "toxtricity-low-key-gmax":
    "https://archives.bulbagarden.net/media/upload/thumb/a/a9/HOME0849Gi.png/200px-HOME0849Gi.png",
  "sandy-shocks": "sandyshocks",
  "miraidon-low-power-mode": "miraidon",
  "miraidon-drive-mode": "miraidon",
  "miraidon-aquatic-mode": "miraidon",
  "miraidon-glide-mode": "miraidon",
  "morpeko-full-belly": "morpeko",
  morpeko: "morpeko-hangry",
  "shaymin-land": "shaymin",
  "lurantis-totem": "lurantis",
  "ogerpon-teal": "ogerpon",
  "brute-bonnet": "brutebonnet",
  "iron-leaves": "ironleaves",
  "mr-mime-galar": "mrmime-galar",
  "darmanitan-galar-zen": "darmanitan-galarzen",
  "mr-rime": "mrrime",
  "tauros-paldea-combat": "tauros-paldeacombat",
  "tauros-paldea-blaze": "tauros-paldeablaze",
  "tauros-paldea-aqua": "tauros-paldeaaqua",
  "koraidon-limited-build": "koraidon",
  "koraidon-sprinting-build": "koraidon",
  "koraidon-swimming-build": "koraidon",
  "koraidon-gliding-build": "koraidon",
  "urshifu-single-strike-gmax": "urshifu-gmax",
  "urshifu-rapid-strike-gmax": "urshifu-rapidstrikegmax",
  "salazzle-totem": "salazzle",
  "great-tusk": "greattusk",
  "iron-treads": "irontreads",
  "mr-mime": "mrmime",
  "deoxys-normal": "deoxys",
  "mime-jr": "mimejr",
  "meowstic-male": "meowstic",
  "meowstic-female": "meowstic-f",
  "indeedee-male": "indeedee",
  "ribombee-totem": "ribombee",
  "vikavolt-totem": "vikavolt",
  "slither-wing": "slitherwing",
  "rockruff-own-tempo": "rockruff",
  "minior-orange-meteor": "minior-meteor",
  "minior-yellow-meteor": "minior-meteor",
  "minior-green-meteor": "minior-meteor",
  "minior-blue-meteor": "minior-meteor",
  "minior-indigo-meteor": "minior-meteor",
  "minior-violet-meteor": "minior-meteor",
  "iron-thorns": "ironthorns",
  "iron-boulder": "ironboulder",
  "mimikyu-totem-disguised": "mimikyu",
  "mimikyu-totem-busted": "mimikyu-busted",
  "zygarde-50": "zygarde",
  "zygarde-10%-power-construct": "zygarde-10",
  "zygarde-50%-power-construct": "zygarde",
  "hakamo-o": "hakamoo",
  "kommo-o": "kommoo",
  "kommo-o-totem": "kommoo",
  zygarde: "zygarde-complete",
  "iron-jugulis": "ironjugulis",
  "wo-chien": "wochien",
  "iron-crown": "ironcrown",
  "scream-tail": "screamtail",
  "iron-valiant": "ironvaliant",
  "enamorus-incarnate": "enamorus",
  "type-null": "typenull",
};
export const formatName = (name: string): string => {
  const normalized = name.toLowerCase().replace(/[^a-z0-9-]/g, "");
  const mapped = spriteNameMap[normalized];
  if (normalized === "ting-lu") {
    return "https://play.pokemonshowdown.com/sprites/gen5/tinglu.png";
  }
  return mapped?.startsWith("http")
    ? mapped
    : `https://play.pokemonshowdown.com/sprites/gen5/${
        mapped || normalized
      }.png`;
};

export type TournamentType = "Smogon" | "Worlds";
export const tournaments = {
  Worlds: {
    years: [2022, 2023, 2024],
  },
  Smogon: {
    years: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024],
  },
};

export const typeColors: Record<string, string> = {
  normal: "#A8A878",
  fire: "#F08030",
  water: "#6890F0",
  electric: "#F8D030",
  grass: "#78C850",
  ice: "#98D8D8",
  fighting: "#C03028",
  poison: "#A040A0",
  ground: "#E0C068",
  flying: "#A890F0",
  psychic: "#F85888",
  bug: "#A8B820",
  rock: "#B8A038",
  ghost: "#705898",
  dragon: "#7038F8",
  dark: "#705848",
  steel: "#B8B8D0",
  fairy: "#EE99AC",
};

export const generations = [
  "generation-i",
  "generation-ii",
  "generation-iii",
  "generation-iv",
  "generation-v",
  "generation-vi",
  "generation-vii",
  "generation-viii",
  "generation-ix",
];
